/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarModelList;
import javax.swing.JPanel;
import Business.Car;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pradnya
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    private JPanel userMethodCont;
    private CarModelList carlistInfo;
    private ArrayList<String> brands;
    //private int manufactured_year;
   

    
       
    SearchJPanel(JPanel userProcessContainer, CarModelList carinformationList) {
        initComponents();
        this.userMethodCont=userProcessContainer;
        this.carlistInfo= carinformationList;
      //  this.manufactured_year=manufactured_year;
        populateTable();
    
    }

    
 private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblView.getModel(); 
        dtm.setRowCount(0);
        for (Car car : carlistInfo.getListCar()){
            Object[] row = new Object[10];
            row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
            row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
            brands= new ArrayList<>();
            brands.add(car.getBrnd());
    }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textDOM = new javax.swing.JTextField();
        btnMgDt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textSerialNo = new javax.swing.JTextField();
        btnSerialNos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textBrnd = new javax.swing.JTextField();
        btnBrnd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textModelNo = new javax.swing.JTextField();
        btnModelNo = new javax.swing.JButton();
        btnMaintExp = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textCityNme = new javax.swing.JTextField();
        butnCity = new javax.swing.JButton();
        textMaxSeating = new javax.swing.JTextField();
        textMinSeating = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        minseats = new javax.swing.JLabel();
        btnmxmi = new javax.swing.JButton();
        jButn1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jBtn2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Custom Search");

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Manufactured Year", "Max_Seats", "Min_Seats", "Serial Number", "Model Number", "Available City", "Availability", "Maintainance Cert", "Created On"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblView);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search by Manufacturing Date:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Date");

        textDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDOMActionPerformed(evt);
            }
        });

        btnMgDt.setText("Search");
        btnMgDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMgDtActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search by Serial Number:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter SNo");

        textSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSerialNoActionPerformed(evt);
            }
        });

        btnSerialNos.setText("Search");
        btnSerialNos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNosActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Search by Brand:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Brand");

        textBrnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBrndActionPerformed(evt);
            }
        });

        btnBrnd.setText("Search");
        btnBrnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrndActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search by ModelNumber:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter Mod No:");

        textModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textModelNoActionPerformed(evt);
            }
        });

        btnModelNo.setText("Search");
        btnModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNoActionPerformed(evt);
            }
        });

        btnMaintExp.setText("Cars withExpired Maintainance Certificate");
        btnMaintExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintExpActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Search Car Availability by City");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter City:");

        textCityNme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCityNmeActionPerformed(evt);
            }
        });

        butnCity.setText("Search");
        butnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnCityActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Max Seats");

        minseats.setForeground(new java.awt.Color(255, 255, 255));
        minseats.setText("Min Seats");

        btnmxmi.setText("Search");
        btnmxmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmxmiActionPerformed(evt);
            }
        });

        jButn1.setText("Get Manufacturers List");
        jButn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButn1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Search by Maximum and Minimum seats");

        jBtn2.setText("BACK");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(459, 459, 459))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMaintExp, javax.swing.GroupLayout.PREFERRED_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jLabel13)
                            .addComponent(jButn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(252, 252, 252))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(34, 34, 34)
                                            .addComponent(textCityNme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModelNo)
                                    .addComponent(butnCity)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(textSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(textDOM, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnMgDt)
                                                .addGap(226, 226, 226)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(minseats)))
                                            .addComponent(btnSerialNos)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(154, 154, 154)
                                        .addComponent(btnBrnd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(textBrnd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnmxmi)
                                    .addComponent(textMaxSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textMinSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 338, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textDOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMgDt)
                    .addComponent(textMaxSeating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minseats)
                    .addComponent(textMinSeating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSerialNos))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textBrnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrnd)
                            .addComponent(btnMaintExp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jButn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnmxmi)
                        .addGap(241, 241, 241)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModelNo))
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textCityNme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butnCity))
                .addGap(112, 112, 112)
                .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMgDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMgDtActionPerformed
      
      
        try{
        int manufactured_year = (Integer.parseInt(textDOM.getText()));
        ArrayList<Car> result = carlistInfo.getMfgList(manufactured_year);
        
        
        if (result==null){
            JOptionPane.showMessageDialog(null, "Invalid Year");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tblView.getModel();
       dtm.setRowCount(0);
       for(Car car : result){
           Object[] row = new Object[10];
            row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
            row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
     }
    }//GEN-LAST:event_btnMgDtActionPerformed
        }catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid Year");
        }
        }
        
        
        
    private void btnSerialNosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNosActionPerformed
        // TODO add your handling code here:
        
        try{
        int serial_num = (Integer.parseInt(textSerialNo.getText()));
        ArrayList<Car> result = carlistInfo.getSerialList(serial_num);
        if (result==null){
            JOptionPane.showMessageDialog(null, "Invalid Serial Number");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tblView.getModel();
       dtm.setRowCount(0);
       for(Car car : result){
           Object[] row = new Object[10];
           row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
             row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
     }
    }             
        }catch(NumberFormatException e){JOptionPane.showMessageDialog(null, "Invalid Serial Number");}  
    }//GEN-LAST:event_btnSerialNosActionPerformed

    private void textSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSerialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSerialNoActionPerformed

    private void textBrndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBrndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBrndActionPerformed

    private void btnBrndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrndActionPerformed
        // TODO add your handling code here:
        String brand = textBrnd.getText();
        ArrayList<Car> result = carlistInfo.getBrandList(brand);
        
        if (result==null){
            JOptionPane.showMessageDialog(null, "Invalid Brand");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tblView.getModel();
       dtm.setRowCount(0);
       for(Car car : result){
           Object[] row = new Object[10];
           row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
            row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
     }
    }             
    }//GEN-LAST:event_btnBrndActionPerformed

    private void textModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textModelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textModelNoActionPerformed

    private void btnModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNoActionPerformed
        // TODO add your handling code here:
        String model_num = textModelNo.getText();
        ArrayList<Car> result = carlistInfo.getModelList(model_num);
        
          if (result.equals("")){
            JOptionPane.showMessageDialog(null, "Invalid Model Number");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tblView.getModel();
       dtm.setRowCount(0);
       for(Car car : result){
           Object[] row = new Object[10];
           row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
            row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
     }
    } 
    }//GEN-LAST:event_btnModelNoActionPerformed

    private void btnMaintExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintExpActionPerformed
        // TODO add your handling code here:
         ArrayList<Car> result = carlistInfo.getMaintainanceCertificate();
        
          if (result==null){
            JOptionPane.showMessageDialog(null, "Invalid Model Number");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tblView.getModel();
       dtm.setRowCount(0);
       for(Car car : result){
           Object[] row = new Object[10];
           row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
            row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
     }
    } 
        
    }//GEN-LAST:event_btnMaintExpActionPerformed

    private void textCityNmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCityNmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCityNmeActionPerformed

    private void butnCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnCityActionPerformed
        // TODO add your handling code here:
         String availble_city = textCityNme.getText();
        ArrayList<Car> result = carlistInfo.getAvailableCarsbyCity(availble_city);
        
          if (result==null){
            JOptionPane.showMessageDialog(null, "Invalid Model Number");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tblView.getModel();
       dtm.setRowCount(0);
       for(Car car : result){
           Object[] row = new Object[10];
           row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
            row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
     }
    } 
        
        
    }//GEN-LAST:event_butnCityActionPerformed

    private void btnmxmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmxmiActionPerformed
        // TODO add your handling code here:
        try{
        
        int max_seats = (Integer.parseInt(textMaxSeating.getText()));
        int min_seats = (Integer.parseInt(textMinSeating.getText()));
        ArrayList<Car> result = carlistInfo.getMaxMinList(max_seats, min_seats);
        
        
            if (result==null){
            JOptionPane.showMessageDialog(null, "Invalid Model Number");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tblView.getModel();
       dtm.setRowCount(0);
       for(Car car : result){
           Object[] row = new Object[10];
           row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
            row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
            
            
     }
            }     
        }catch(NumberFormatException c){JOptionPane.showMessageDialog(null, "Invalid entry");} 
    }//GEN-LAST:event_btnmxmiActionPerformed

    private void jButn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButn1ActionPerformed
        // TODO add your handling code here:
        
        ArrayList<String> car = carlistInfo.getAllBrands();
        Set<String> setString = new HashSet<String>(car);
        ArrayList<String> finalList = new ArrayList<>(setString);
        
        
        DefaultTableModel dtm = (DefaultTableModel) tblView.getModel();
       dtm.setRowCount(0);
       for (String c : finalList)
       {
       Object[] row = new Object [10];
       row[0]=c;
       dtm.addRow(row);
       
       }
        
        
    }//GEN-LAST:event_jButn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        // TODO add your handling code here:
        
        userMethodCont.remove(this);
           CardLayout layout = (CardLayout) userMethodCont.getLayout();
           layout.previous(userMethodCont);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void textDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDOMActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrnd;
    private javax.swing.JButton btnMaintExp;
    private javax.swing.JButton btnMgDt;
    private javax.swing.JButton btnModelNo;
    private javax.swing.JButton btnSerialNos;
    private javax.swing.JButton btnmxmi;
    private javax.swing.JButton butnCity;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jButn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minseats;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField textBrnd;
    private javax.swing.JTextField textCityNme;
    private javax.swing.JTextField textDOM;
    private javax.swing.JTextField textMaxSeating;
    private javax.swing.JTextField textMinSeating;
    private javax.swing.JTextField textModelNo;
    private javax.swing.JTextField textSerialNo;
    // End of variables declaration//GEN-END:variables
}
