/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Car;
import Business.CarModelList;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Date;
import java.sql.Timestamp;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pradnya
 */
public class UpdateJPanel extends javax.swing.JPanel {

    private JPanel userMethodCont;
    private CarModelList carListInfo;
    private Car c;
    
    private Date date;
    private Timestamp timestamp;
    
    public static String Time;

    public static String getTime() {
        return Time;
    }

    public static void setTime(String Time) {
        UpdateJPanel.Time = Time;
    }
   
    public UpdateJPanel(JPanel userProcessContainer, CarModelList carinformationlist) {
        initComponents();
        this.userMethodCont=userProcessContainer;
       this.carListInfo=carinformationlist;
       
       populateTable();
       
       
     
       
    }
    
    
    
    private void populateCarDetails(){
       
        int selectedrow =tblView.getSelectedRow();
        c = (Car) tblView.getValueAt(selectedrow, 0);
        
        
        
        textYrOfMfg.setText(String.valueOf(c.getManu_year()));
        textBrnd.setText(c.getBrnd());
        textCity.setText(c.getAvailbilityCity());
        textMaxSeating.setText(String.valueOf(c.getMaxNoseating()));
        textMinSeating.setText(String.valueOf(c.getMinSeating()));
        textModelNo.setText(c.getModelNo());
        textSerialNo.setText(String.valueOf(c.getSerialNo()));
        if(c.isAvb()==true)
            rbYesAvail.setSelected(true);
        
        else
            rbNoAvail.setSelected(true);
        
        if(c.isMaint_cert()==true)
            rbYesMaint.setSelected(true);
        else
            rbNoMaint.setSelected(true);
        
        
        
        
        
        
        
    }
    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblView.getModel(); 
        dtm.setRowCount(0);
        for (Car car : carListInfo.getListCar()){
            Object[] row = new Object[10];
            row[0] = car;
            row[1] = car.getManu_year();
            row[2]= car.getMaxNoseating();
            row[3]= car.getMinSeating();
            row[4]=car.getSerialNo();
            row[5]=car.getModelNo();
            row[6]=car.getAvailbilityCity();
            row[7]=car.isAvb();
            row[8]=car.isMaint_cert();
            row[9]=car.getCreatOn();
            dtm.addRow(row);
            
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        rbNoAvail = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        textYrOfMfg = new javax.swing.JTextField();
        textBrnd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textMaxSeating = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textSerialNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textMinSeating = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textModelNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbYesMaint = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        textCity = new javax.swing.JTextField();
        rbNoMaint = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rbYesAvail = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        buttnUpdate = new javax.swing.JButton();
        buttnSave = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Manufactured Year", "Max_Seats", "Min_Seats", "Serial Number", "Model Number", "Available City", "Availability", "Maintainance Cert", "Created On"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblView);

        buttonGroup2.add(rbNoAvail);
        rbNoAvail.setText("No");
        rbNoAvail.setEnabled(false);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Availability");

        textYrOfMfg.setEnabled(false);

        textBrnd.setEnabled(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Brand");

        textMaxSeating.setEnabled(false);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Year of Manufacture");

        textSerialNo.setEnabled(false);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Minimum Seats");

        textMinSeating.setEnabled(false);
        textMinSeating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMinSeatingActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Maximum Seats");

        textModelNo.setEnabled(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Serial Number");

        buttonGroup1.add(rbYesMaint);
        rbYesMaint.setForeground(new java.awt.Color(255, 255, 255));
        rbYesMaint.setText("Yes");
        rbYesMaint.setEnabled(false);
        rbYesMaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbYesMaintActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Model Number");

        textCity.setEnabled(false);

        buttonGroup1.add(rbNoMaint);
        rbNoMaint.setForeground(new java.awt.Color(255, 255, 255));
        rbNoMaint.setText("No");
        rbNoMaint.setEnabled(false);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Available City");

        buttonGroup2.add(rbYesAvail);
        rbYesAvail.setText("Yes");
        rbYesAvail.setEnabled(false);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Maintainance Certificate");

        buttnUpdate.setText("Update");
        buttnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttnUpdateActionPerformed(evt);
            }
        });

        buttnSave.setBackground(new java.awt.Color(255, 255, 255));
        buttnSave.setText("Save");
        buttnSave.setEnabled(false);
        buttnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttnSaveActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(183, 183, 183)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textModelNo)
                                        .addComponent(textSerialNo)
                                        .addComponent(textBrnd)
                                        .addComponent(textMaxSeating)
                                        .addComponent(textYrOfMfg)
                                        .addComponent(textMinSeating)
                                        .addComponent(textCity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbYesMaint)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbNoMaint))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbYesAvail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbNoAvail))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(415, 415, 415)
                        .addComponent(lblTime)
                        .addContainerGap(284, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
                        .addGap(145, 145, 145))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblTime))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textBrnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textYrOfMfg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textMinSeating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textMaxSeating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(textCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rbYesMaint)
                            .addComponent(rbNoMaint))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(rbYesAvail)
                            .addComponent(rbNoAvail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textMinSeatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMinSeatingActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textMinSeatingActionPerformed

    private void rbYesMaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbYesMaintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbYesMaintActionPerformed

    private void buttnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttnUpdateActionPerformed
        // TODO add your handling code here:
        textBrnd.setEnabled(true);
        textCity.setEnabled(true);
        textMaxSeating.setEnabled(true);
        textMinSeating.setEnabled(true);
        textModelNo.setEnabled(true);
        textSerialNo.setEnabled(true);
        textYrOfMfg.setEnabled(true);
        rbNoAvail.setEnabled(true);
        rbNoMaint.setEnabled(true);
        rbYesAvail.setEnabled(true);
        rbYesMaint.setEnabled(true);
        buttnUpdate.setEnabled(false);
        buttnSave.setEnabled(true);
         populateCarDetails();
    }//GEN-LAST:event_buttnUpdateActionPerformed

    private void buttnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttnSaveActionPerformed
        // TODO add your handling code here:
        
        try{
            
            if(textBrnd.getText().equals("") || textCity.getText().equals("") || textModelNo.getText().equals(""))
        JOptionPane.showMessageDialog(null,"Fields cannot be empty");
            
            else{
        c.setBrnd(textBrnd.getText());
        c.setManacyear(Integer.parseInt(textYrOfMfg.getText()));
        c.setAvailbilityCity(textCity.getText());
        c.setMaxSeating(Integer.parseInt(textMaxSeating.getText()));
        c.setMinSeating(Integer.parseInt(textMinSeating.getText()));
        if(rbNoAvail.isSelected()==true)
            c.setAvb(false);
        if(rbYesAvail.isSelected()==true)
            c.setAvb(true);
        if(rbNoMaint.isSelected()==true)
            c.setMaint_cert(false);
        if(rbYesMaint.isSelected()==true)
            c.setMaint_cert(true);
        c.setModelNo(textModelNo.getText());
        c.setSerialNo(Integer.parseInt(textSerialNo.getText()));
        populateTable();
        JOptionPane.showMessageDialog(null,"Car Specifics Updated Successfully");
        buttnUpdate.setEnabled(true);
        buttnSave.setEnabled(false);
         textBrnd.setEnabled(false);
        textCity.setEnabled(false);
        textMaxSeating.setEnabled(false);
        textMinSeating.setEnabled(false);
        textModelNo.setEnabled(false);
        textSerialNo.setEnabled(false);
        textYrOfMfg.setEnabled(false);
        rbNoAvail.setEnabled(false);
        rbNoMaint.setEnabled(false);
        rbYesAvail.setEnabled(false);
        rbYesMaint.setEnabled(false);
        date =new Date();
        long Timme = date.getTime();
        timestamp= new Timestamp(Timme);
        Time= String.valueOf(timestamp);
        
        lblTime.setText(Time);
        
        
            }
        
        }catch(NumberFormatException c){JOptionPane.showMessageDialog(null, "Enter numeric value");}
    }//GEN-LAST:event_buttnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userMethodCont.remove(this);
           CardLayout layout = (CardLayout) userMethodCont.getLayout();
           layout.previous(userMethodCont);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttnSave;
    private javax.swing.JButton buttnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JRadioButton rbNoAvail;
    private javax.swing.JRadioButton rbNoMaint;
    private javax.swing.JRadioButton rbYesAvail;
    private javax.swing.JRadioButton rbYesMaint;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField textBrnd;
    private javax.swing.JTextField textCity;
    private javax.swing.JTextField textMaxSeating;
    private javax.swing.JTextField textMinSeating;
    private javax.swing.JTextField textModelNo;
    private javax.swing.JTextField textSerialNo;
    private javax.swing.JTextField textYrOfMfg;
    // End of variables declaration//GEN-END:variables
}
