/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Neha
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    
    private UserAccount userAccount;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        
        this.userAccount = account;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rqstTestJBtn = new javax.swing.JButton();
        jLab1 = new javax.swing.JLabel();
        msgJTxtField = new javax.swing.JTextField();
        bckBtn = new javax.swing.JButton();
        valLab = new javax.swing.JLabel();
        entrpriseLab = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rqstTestJBtn.setText("Request Test");
        rqstTestJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rqstTestJBtnActionPerformed(evt);
            }
        });
        add(rqstTestJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 95, -1, -1));

        jLab1.setText("Message");
        add(jLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 40, -1, -1));
        add(msgJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 37, 89, -1));

        bckBtn.setText("<<Back");
        bckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckBtnActionPerformed(evt);
            }
        });
        add(bckBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        valLab.setText("<value>");
        add(valLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, -1));

        entrpriseLab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entrpriseLab.setText("EnterPrise :");
        add(entrpriseLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void rqstTestJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rqstTestJBtnActionPerformed
        
        
        
    }//GEN-LAST:event_rqstTestJBtnActionPerformed

    private void bckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckBtnActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAreaJPanel dwjp = (CustomerAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_bckBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckBtn;
    private javax.swing.JLabel entrpriseLab;
    private javax.swing.JLabel jLab1;
    private javax.swing.JTextField msgJTxtField;
    private javax.swing.JButton rqstTestJBtn;
    private javax.swing.JLabel valLab;
    // End of variables declaration//GEN-END:variables
}
