/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;

import Business.Organization;
import Business.UserAccount.UserAccount;
import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.Menu.MenuDirectory;
import Business.Order.OrderDirectory;
import Business.Restaurant.RestaurantDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Neha
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private UserAccount userAccount;
    private JPanel userProcessContainer;
    private CustomerDirectory customerDirectory;
    private RestaurantDirectory restaurantDirectory;
    private DeliveryManDirectory deliveryManDirectory;
    private MenuDirectory menuDirectory;
    private OrderDirectory orderDirectory;

    public MainJFrame() {
        initComponents();
        
        system = dB4OUtil.retrieveSystem();
        this.setSize(1680, 1050);
        //system.setCustomerDirectory(new CustomerDirectory());
        customerDirectory = new CustomerDirectory();
        restaurantDirectory = new RestaurantDirectory();
        deliveryManDirectory = new DeliveryManDirectory();
        menuDirectory = new MenuDirectory();
        orderDirectory = new OrderDirectory();
//        system.setDeliveryManDirectory(new DeliveryManDirectory());
//        system.setMenuDirectory(new MenuDirectory());
//        system.setRestaurantDirectory(new RestaurantDirectory());
//        system.setOrderDirectory(new OrderDirectory());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        smallBox = new javax.swing.JPanel();
        loginJBtn = new javax.swing.JButton();
        userNameJTextBox = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jBox1 = new javax.swing.JLabel();
        jBox2 = new javax.swing.JLabel();
        loginJLbl = new javax.swing.JLabel();
        logoutJBtn = new javax.swing.JButton();
        jBox = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginJBtn.setText("Login");
        loginJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJBtnActionPerformed(evt);
            }
        });

        userNameJTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextBoxActionPerformed(evt);
            }
        });

        jBox1.setText("User Name");

        jBox2.setText("Password");

        logoutJBtn.setText("Logout");
        logoutJBtn.setEnabled(false);
        logoutJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout smallBoxLayout = new javax.swing.GroupLayout(smallBox);
        smallBox.setLayout(smallBoxLayout);
        smallBoxLayout.setHorizontalGroup(
            smallBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smallBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(smallBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(passField, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(jBox1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBox2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userNameJTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, smallBoxLayout.createSequentialGroup()
                            .addComponent(logoutJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addGap(26, 26, 26)
                            .addComponent(loginJLbl)))
                    .addComponent(loginJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        smallBoxLayout.setVerticalGroup(
            smallBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smallBoxLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameJTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginJBtn)
                .addGap(34, 34, 34)
                .addComponent(logoutJBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginJLbl)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(smallBox);

        jBox.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jBox);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJBtnActionPerformed
        // Get user name
        if(userNameJTextBox.getText().isEmpty() || passField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Username and Password field's cannot be empty");
            return;
        }
        
        else if(system.getUserAccountDirectory().authenticateUser(userNameJTextBox.getText(), passField.getText()) == null) {
            JOptionPane.showMessageDialog(null,"Invalid UserName");
            return;
        }
        
        
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userNameJTextBox.getText(), passField.getText());
        
        System.out.println("EcoSYSTEM MAIN" + system.toString() + system.getUserAccountDirectory().getUserAccountList().size());
        
        CardLayout layout = (CardLayout) jBox.getLayout();
        jBox.add("workArea",userAccount.getRole().createWorkArea(jBox, userAccount, system, customerDirectory, restaurantDirectory, deliveryManDirectory, menuDirectory, orderDirectory));
        layout.next(jBox);
        logoutJBtn.setEnabled(true);
        loginJBtn.setEnabled(false);
        
    }//GEN-LAST:event_loginJBtnActionPerformed

    private void logoutJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJBtnActionPerformed
        logoutJBtn.setEnabled(false);
        userNameJTextBox.setEnabled(true);
        passField.setEnabled(true);
        loginJBtn.setEnabled(true);

        userNameJTextBox.setText("");
        passField.setText("");

        jBox.removeAll();
        JPanel blankJP = new JPanel();
        jBox.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) jBox.getLayout();
        crdLyt.next(jBox);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutJBtnActionPerformed

    private void userNameJTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBox;
    private javax.swing.JLabel jBox1;
    private javax.swing.JLabel jBox2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJBtn;
    private javax.swing.JLabel loginJLbl;
    private javax.swing.JButton logoutJBtn;
    private javax.swing.JPasswordField passField;
    private javax.swing.JPanel smallBox;
    private javax.swing.JTextField userNameJTextBox;
    // End of variables declaration//GEN-END:variables
}
