

package userinterface.RestaurantAdminRole;


import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Menu.MenuDirectory;
import Business.Order.OrderDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  Neha
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcContain;
    private UserAccount accnt;
    private EcoSystem ecoSys;
    private CustomerDirectory customDirect;
    private RestaurantDirectory restrentDirect;
    private DeliveryManDirectory delivManDirect;
    private MenuDirectory menuDirect;
    private OrderDirectory orderDirect;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, 
            CustomerDirectory customerDirectory, RestaurantDirectory restaurantDirectory, 
            DeliveryManDirectory deliveryManDirectory, MenuDirectory menuDirectory, OrderDirectory orderDirectory) {
        initComponents();
        this.userProcContain = userProcessContainer;
        this.accnt = account;
        this.ecoSys = ecoSystem;
        this.customDirect = ecoSystem.getCustomerDirectory();
        this.restrentDirect = ecoSystem.getRestaurantDirectory();
        this.delivManDirect = ecoSystem.getDeliveryManDirectory();
        this.menuDirect = ecoSystem.getMenuDirectory();
        this.orderDirect = ecoSystem.getOrderDirectory();
        valLab.setText(account.getUsername());
                
                
        
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab1 = new javax.swing.JLabel();
        userJBtn = new javax.swing.JButton();
        manageEmpJBtn = new javax.swing.JButton();
        manageOrganJBtn = new javax.swing.JButton();
        enterpriseLab = new javax.swing.JLabel();
        valLab = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLab1.setText("My Work Area -Adminstrative Role");
        add(jLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        userJBtn.setText("Manage Restaurant Info");
        userJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJBtnActionPerformed(evt);
            }
        });
        add(userJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 230, -1));

        manageEmpJBtn.setText("Manage menu");
        manageEmpJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmpJBtnActionPerformed(evt);
            }
        });
        add(manageEmpJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 230, -1));

        manageOrganJBtn.setText("Manage Orders");
        manageOrganJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganJBtnActionPerformed(evt);
            }
        });
        add(manageOrganJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 230, -1));

        enterpriseLab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLab.setText("Restaurant :");
        add(enterpriseLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valLab.setText("<value>");
        add(valLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJBtnActionPerformed
        // TODO add your handling code here:
        ManageRestaurantInfoJPanel mrijp = new ManageRestaurantInfoJPanel(userProcContain,accnt, ecoSys, restrentDirect);
        userProcContain.add("manageMenuJPanel",mrijp);
        CardLayout layout = (CardLayout) userProcContain.getLayout();
        layout.next(userProcContain);
        
    }//GEN-LAST:event_userJBtnActionPerformed

    private void manageEmpJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmpJBtnActionPerformed

        ManageMenuJPanel manageMenuJPanel = new ManageMenuJPanel(userProcContain,accnt, ecoSys, restrentDirect,menuDirect);
        userProcContain.add("manageMenuJPanel",manageMenuJPanel);
        CardLayout layout = (CardLayout) userProcContain.getLayout();
        layout.next(userProcContain);
    }//GEN-LAST:event_manageEmpJBtnActionPerformed

    private void manageOrganJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganJBtnActionPerformed

        ManageOrderJPanel manageOrderJPanel = new ManageOrderJPanel(userProcContain,accnt, ecoSys, restrentDirect,menuDirect, orderDirect);
        userProcContain.add("ManageOrderJPanel",manageOrderJPanel);
        CardLayout layout = (CardLayout) userProcContain.getLayout();
        layout.next(userProcContain);
    }//GEN-LAST:event_manageOrganJBtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLab;
    private javax.swing.JLabel jLab1;
    private javax.swing.JButton manageEmpJBtn;
    private javax.swing.JButton manageOrganJBtn;
    private javax.swing.JButton userJBtn;
    private javax.swing.JLabel valLab;
    // End of variables declaration//GEN-END:variables
    
}
