/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Order.Order;
import Business.Order.OrderDirectory;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neha
 */
public class DeliveryManWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DeliveryManDirectory deliveryManDirectory;
    private OrderDirectory orderDirectory;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public DeliveryManWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, DeliveryManDirectory deliveryManDirectory, OrderDirectory orderDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.orderDirectory = business.getOrderDirectory();
        this.deliveryManDirectory = business.getDeliveryManDirectory();
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) workReqstJTab.getModel();
        model.setRowCount(0);
        for (Order order : business.getOrderDirectory().getOrderDirectory()) {
            if (order.getOrderStatus() != null && order.getOrderStatus().equals("Order Ready for Pick up")) {
                Object[] row = new Object[7];
                row[0] = order;
                row[1] = order.getMessage();
                row[2] = order.getOrderStatus();
                row[3] = order.getCustomer().getName();
                row[4] = order.getCustomer().getHomeAddress();
                row[5] = order.getRestaurant().getRestaurantName();
                row[6] = order.getRestaurant().getAddress();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrlPan1 = new javax.swing.JScrollPane();
        workReqstJTab = new javax.swing.JTable();
        assinJBtn = new javax.swing.JButton();
        procJBtn = new javax.swing.JButton();
        refhJBtn = new javax.swing.JButton();
        jSclPan2 = new javax.swing.JScrollPane();
        tblDeliveryMan = new javax.swing.JTable();
        jLab1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workReqstJTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Message", "Status", "Customer", "Customer Address", "Restaurant", "Restaurant Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrlPan1.setViewportView(workReqstJTab);
        if (workReqstJTab.getColumnModel().getColumnCount() > 0) {
            workReqstJTab.getColumnModel().getColumn(1).setResizable(false);
            workReqstJTab.getColumnModel().getColumn(2).setResizable(false);
            workReqstJTab.getColumnModel().getColumn(4).setResizable(false);
            workReqstJTab.getColumnModel().getColumn(5).setResizable(false);
            workReqstJTab.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrlPan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1060, 96));

        assinJBtn.setText("Assign to me");
        assinJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assinJBtnActionPerformed(evt);
            }
        });
        add(assinJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        procJBtn.setText("Process");
        procJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procJBtnActionPerformed(evt);
            }
        });
        add(procJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 480, 190, -1));

        refhJBtn.setText("Refresh");
        refhJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refhJBtnActionPerformed(evt);
            }
        });
        add(refhJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, -1, -1));

        tblDeliveryMan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Customer Address", "Restaurant", "Restaurant Address", "Status"
            }
        ));
        jSclPan2.setViewportView(tblDeliveryMan);
        if (tblDeliveryMan.getColumnModel().getColumnCount() > 0) {
            tblDeliveryMan.getColumnModel().getColumn(0).setResizable(false);
            tblDeliveryMan.getColumnModel().getColumn(1).setResizable(false);
            tblDeliveryMan.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jSclPan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 1060, 180));

        jLab1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLab1.setText("Delivery Man Page");
        add(jLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assinJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assinJBtnActionPerformed

        int selectedRow = workReqstJTab.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        
        Order order = (Order) workReqstJTab.getValueAt(selectedRow,0);
        order.setDeliveryMan(userAccount.getEmployee().getName());
        order.setOrderStatus("Order Picked up");
        populateTable();
        populateDeliveryManTable();
                
    }//GEN-LAST:event_assinJBtnActionPerformed

    public void populateDeliveryManTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblDeliveryMan.getModel();
        model.setRowCount(0);
        for (Order order : business.getOrderDirectory().getOrderDirectory()) {
            if (order.getDeliveryMan() != null && order.getDeliveryMan().equals(userAccount.getEmployee().getName())) {
                Object[] row = new Object[6];
                row[0] = order;
                row[1] = order.getCustomer().getName();
                row[2] = order.getCustomer().getHomeAddress();
                row[3] = order.getRestaurant().getRestaurantName();
                row[4] = order.getRestaurant().getAddress();
                row[5] = order.getOrderStatus();
                model.addRow(row);
            }
        }
    }
    
    private void procJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procJBtnActionPerformed
        
        int selectedRow = tblDeliveryMan.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        
        
        Order order = (Order) tblDeliveryMan.getValueAt(selectedRow, 0);
        if(order.getOrderStatus().equals("Delivered")) {
            JOptionPane.showMessageDialog(null, "Already Delivered.");
            return;
        }
        order.setOrderStatus("Delivered");
        //orderDirectory.getOrderDirectory().remove(order);
        
        JOptionPane.showMessageDialog(null, "Delivered");
        populateDeliveryManTable();
        
    }//GEN-LAST:event_procJBtnActionPerformed

    private void refhJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refhJBtnActionPerformed
        populateTable();
    }//GEN-LAST:event_refhJBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assinJBtn;
    private javax.swing.JLabel jLab1;
    private javax.swing.JScrollPane jSclPan2;
    private javax.swing.JScrollPane jScrlPan1;
    private javax.swing.JButton procJBtn;
    private javax.swing.JButton refhJBtn;
    private javax.swing.JTable tblDeliveryMan;
    private javax.swing.JTable workReqstJTab;
    // End of variables declaration//GEN-END:variables
}
