/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInteface.Person;

import business.VerifierNumeric;
import business.VerifierString;
import business.Person;
import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pradnya
 */
public class ViewUpdatePersonDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientDetailsJPanel
     */
    private Person person;
    private JPanel userProcessContainer;
    private Boolean isEdit = Boolean.FALSE;

    public ViewUpdatePersonDetailsJPanel(JPanel userProcessContainer, Person person, Boolean isEdit) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        this.isEdit = isEdit;
        addVerifiers();
        populatePatientDetails();
        modifyTextFields(this.isEdit);
    }

    private void addVerifiers() {
        InputVerifier integerVerifier = new VerifierNumeric();
        viewPersonAgeJTextField.setInputVerifier(integerVerifier);
        InputVerifier stringVerifier = new VerifierString();
        viewPersonNameJTextField.setInputVerifier(stringVerifier);
    }

    private void populatePatientDetails() {
        viewPersonNameJTextField.setText(person.getPersonsName());
        viewPersonAgeJTextField.setText(String.valueOf(person.getPersonsAge()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAgeJLabel = new javax.swing.JLabel();
        viewPersonNameJTextField = new javax.swing.JTextField();
        viewPersonAgeJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        viewPatientNameJLabel = new javax.swing.JLabel();
        viewBackJButton = new javax.swing.JButton();
        viewEditJButton = new javax.swing.JButton();
        viewSaveJButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));

        viewAgeJLabel.setText("Age");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Details");

        viewPatientNameJLabel.setText("Patient Name");

        viewBackJButton.setText("<< Back");
        viewBackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBackJButtonActionPerformed(evt);
            }
        });

        viewEditJButton.setText("Edit");
        viewEditJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditJButtonActionPerformed(evt);
            }
        });

        viewSaveJButton.setText("Save");
        viewSaveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSaveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewBackJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewEditJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewSaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewAgeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPatientNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPersonAgeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewPersonNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPersonNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPatientNameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPersonAgeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAgeJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBackJButton)
                    .addComponent(viewEditJButton)
                    .addComponent(viewSaveJButton))
                .addContainerGap(563, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewEditJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditJButtonActionPerformed
        // TODO add your handling code here:
        modifyTextFields(true);
    }//GEN-LAST:event_viewEditJButtonActionPerformed

    private void modifyTextFields(Boolean isEdit) {
        if (isEdit) {
            viewPersonNameJTextField.setEnabled(true);
            viewPersonAgeJTextField.setEnabled(true);
        } else {
            viewPersonNameJTextField.setEnabled(false);
            viewPersonAgeJTextField.setEnabled(false);
        }
    }

    private void viewSaveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSaveJButtonActionPerformed
        // TODO add your handling code here:

        if (checkBlankInput()) {
            person.setPersonsAge(Integer.parseInt(viewPersonAgeJTextField.getText()));
            person.setPersonsName(viewPersonNameJTextField.getText());
            JOptionPane.showMessageDialog(this, "Person updated!!",
                    "Update", JOptionPane.INFORMATION_MESSAGE);
            modifyTextFields(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct values", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_viewSaveJButtonActionPerformed
    private Boolean checkBlankInput() {
        if (viewPersonAgeJTextField.getText().length() == 0
                || viewPersonNameJTextField.getText().length() == 0) {
            return false;
        } else {
            return true;
        }
    }
    private void viewBackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBackJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_viewBackJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel viewAgeJLabel;
    private javax.swing.JButton viewBackJButton;
    private javax.swing.JButton viewEditJButton;
    private javax.swing.JLabel viewPatientNameJLabel;
    private javax.swing.JTextField viewPersonAgeJTextField;
    private javax.swing.JTextField viewPersonNameJTextField;
    private javax.swing.JButton viewSaveJButton;
    // End of variables declaration//GEN-END:variables
}
